### ISSUE TITLE
try to run example on windows7 64, throw java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by xuetaolu** [Zortax/MinecraftInjectionAPI#1]
Trying to attach to Minecraft VM (org.jackhuang.hellominecraft.launcher.Launcher)...
Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.tools.attach.LinuxVirtualMachine.isLinuxThreads()Z
	at sun.tools.attach.LinuxVirtualMachine.isLinuxThreads(Native Method)
	at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:337)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:255)
	at de.zortax.injection.injector.RuntimeInjector.attachToVm(RuntimeInjector.java:26)
	at de.zortax.injection.example.transformer.MinecraftTransformer.main(MinecraftTransformer.java:26)

Shall I change the version of com.sun.tools ?
Or I forget to give a param to distinguish windows from linux?

**Comment by zortax** [comment]
@xuetaolu which version of Java/which VM implementation are you using? Try adding `tools.jar` (can be found in the `libs` directory of your JDK installation) to your classpath before other libraries. It might be problematic if you use the OpenJDK, as it doesn't necessarily contain a `tools.jar`.

**Comment by zortax** [comment]
Also note that this is not something you _should_ use. It's more of a hacky proof on concept/experiment. If you want to use this in a project, you should probably implement it yourself... :–)
